fragment userFragment on User {
  id
  name
  email
  contactNumber
  averageRating
  preferences {
    ...preferencesFragment
  }
  media {
    id
    url
    type
    alt
    createdAt
    userId
  }
}
