import type { Metadata } from 'next';
import './globals.css';
import NextIntlProvider from '@/i18n/NextIntlProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <NextIntlProvider>{children}</NextIntlProvider>
    </html>
  );
};

export default RootLayout;
