mutation CreatePreferences($input: CreatePreferencesInput) {
  createPreferences(input: $input) {
    status {
      status
      errorMessage
    }
    data {
      ...preferencesFragment
    }
  }
}
