#import "./fragments/user.gql"

query GetAllTeams {
  getAllTeams {
    id
    name
    members {
      ...userFragment
    }
  }
}

mutation CreateTeam($input: CreateTeamInput!) {
  createTeam(input: $input) {
    data {
      id
      name
      members {
        ...userFragment
      }
    }
    status {
      errorMessage
      status
    }
  }
}
