#import "./fragments/user.gql"

query GetUserById($userId: ID!) {
  getUserById(userId: $userId) {
    ...userFragment
  }
}

query login($email: String) {
  login(email: $email) {
    ...userFragment
  }
}

query GetAllUsers {
  getAllUsers {
    ...userFragment
  }
}

mutation CreateUser($input: CreateUserInput!) {
  createUser(input: $input) {
    data {
      ...userFragment
    }
    status {
      errorMessage
      status
    }
  }
}

mutation UpdateUser($input: UpdateUserInput!) {
  updateUser(input: $input) {
    data {
      ...userFragment
    }
    status {
      errorMessage
      status
    }
  }
}
